apiVersion: rhpam.kiegroup.org/v1
kind: KogitoBuild
metadata:
  name: rules
  namespace: kogito-rules
spec:
  type: RemoteSource
  #env:
  # env can be used to set variables during build
  #- name: MY_CUSTOM_ENV
  #  value: "my value"
  gitSource:
    uri: "https://github.com/aashishsharmawork/rules"
  # set your maven nexus repository to speed up the build time
  #mavenMirrorURL:
